FROM openjdk
WORKDIR usr/src
ADD ./target/TaskManagementService-0.0.1-SNAPSHOT.jar /usr/src/TaskManagementService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","TaskManagementService-0.0.1-SNAPSHOT.jar"]